/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppleIcon: typeof import('./src/components/AppleIcon.vue')['default']
    AuroraButton: typeof import('./src/components/AuroraButton.vue')['default']
    BreathingGuide: typeof import('./src/components/BreathingGuide.vue')['default']
    EChart: typeof import('./src/components/EChart.vue')['default']
    FeatureTutorial: typeof import('./src/components/FeatureTutorial.vue')['default']
    GlassCard: typeof import('./src/components/GlassCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionTitle: typeof import('./src/components/SectionTitle.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanDialog: typeof import('vant/es')['Dialog']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanLoading: typeof import('vant/es')['Loading']
    VanPopup: typeof import('vant/es')['Popup']
    VanProgress: typeof import('vant/es')['Progress']
    VanSearch: typeof import('vant/es')['Search']
    VanSlider: typeof import('vant/es')['Slider']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
    WhiteNoiseMixer: typeof import('./src/components/WhiteNoiseMixer.vue')['default']
  }
}
